version: 2.1

orbs:
  coverage-reporter: codacy/coverage-reporter@11.3.8

defaults: &defaults
  docker:
    - image: circleci/node:12

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
      - run: npm run test
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - lib
  codacy-coverage-report:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run coverage
      - coverage-reporter/send_report:
          coverage-reports: 'coverage/lcov.info'
          project-token: $CODACY_PROJECT_TOKEN
  npm-publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          npm publish

workflows:
  build_deploy:
    jobs:
      - test
      - codacy-coverage-report:
          requires:
            - test
      - build:
          requires:
            - test
      - npm-publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
          requires:
            - build
