"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GOOD_RESPONSE_STATUS_CODE = exports.Currency = exports.Errors = void 0;
var Errors;
(function (Errors) {
    Errors["PARSING_ERROR"] = "Error while parsing";
    Errors["PRICE_HISTORY_PARSE_ERROR"] = "Error while parsing price history page";
    Errors["PAGE_PARSING_ERROR"] = "Error while parsing steamcommunity page";
    Errors["PROXY_CONNECTION_ERROR"] = "Proxy connection error";
})(Errors = exports.Errors || (exports.Errors = {}));
var Currency;
(function (Currency) {
    Currency[Currency["USD"] = 1] = "USD";
    Currency[Currency["GBP"] = 2] = "GBP";
    Currency[Currency["EUR"] = 3] = "EUR";
    Currency[Currency["CHF"] = 4] = "CHF";
    Currency[Currency["RUB"] = 5] = "RUB";
    Currency[Currency["PLN"] = 6] = "PLN";
    Currency[Currency["BRL"] = 7] = "BRL";
    Currency[Currency["JPY"] = 8] = "JPY";
    Currency[Currency["SEK"] = 9] = "SEK";
    Currency[Currency["IDR"] = 10] = "IDR";
    Currency[Currency["MYR"] = 11] = "MYR";
    Currency[Currency["PHP"] = 12] = "PHP";
    Currency[Currency["SGD"] = 13] = "SGD";
    Currency[Currency["THB"] = 14] = "THB";
    Currency[Currency["VND"] = 15] = "VND";
    Currency[Currency["KRW"] = 16] = "KRW";
    Currency[Currency["TRY"] = 17] = "TRY";
    Currency[Currency["UAH"] = 18] = "UAH";
    Currency[Currency["MXN"] = 19] = "MXN";
    Currency[Currency["CAD"] = 20] = "CAD";
    Currency[Currency["AUD"] = 21] = "AUD";
    Currency[Currency["NZD"] = 22] = "NZD";
    Currency[Currency["CNY"] = 23] = "CNY";
    Currency[Currency["INR"] = 24] = "INR";
    Currency[Currency["CLP"] = 25] = "CLP";
    Currency[Currency["PEN"] = 26] = "PEN";
    Currency[Currency["COP"] = 27] = "COP";
    Currency[Currency["ZAR"] = 28] = "ZAR";
    Currency[Currency["HKD"] = 29] = "HKD";
    Currency[Currency["TWD"] = 30] = "TWD";
    Currency[Currency["SRD"] = 31] = "SRD";
    Currency[Currency["AED"] = 32] = "AED";
    Currency[Currency["ARS"] = 34] = "ARS";
    Currency[Currency["ILS"] = 35] = "ILS";
    Currency[Currency["KZT"] = 37] = "KZT";
    Currency[Currency["KWD"] = 38] = "KWD";
    Currency[Currency["QAR"] = 39] = "QAR";
    Currency[Currency["CRC"] = 40] = "CRC";
    Currency[Currency["UYU"] = 41] = "UYU";
})(Currency = exports.Currency || (exports.Currency = {}));
exports.GOOD_RESPONSE_STATUS_CODE = 200;
