name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'release-*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.13'
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Check code with linter
        run: npm run lint
      - name: Run unit tests
        run: npm run test
      - run: echo "Done"

  codacy-coverage-reporter:
    needs: test
    runs-on: ubuntu-latest
    name: coverage-reporter
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Run unit coverage
        run: npm run coverage
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: 'coverage/lcov.info'

  build:
    needs: test
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Run build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: .

  publish:
    needs: [test, build]
    runs-on: ubuntu-latest
    name: publish
    steps:
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

